import puppeteer from 'puppeteer-core';
const browser = await puppeteer.launch({ executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless:'new', args:['--no-sandbox','--mute-audio'], defaultViewport:{width:390,height:844,isMobile:true,hasTouch:true,deviceScaleFactor:2} });
const page = await browser.newPage();
await page.goto('http://localhost:4173/', { waitUntil:'networkidle0' });
await page.evaluate(()=>localStorage.setItem('maple-quest-save-v3', JSON.stringify({level:300,exp:0,charKey:'warrior',highestByDiff:[20,1,1,1],clearedByDiff:[false,false,false,false],clears:0})));
await page.reload({ waitUntil:'networkidle0' });
await new Promise(r=>setTimeout(r,1800));
await page.evaluate(()=>{ const g=window.__PHASER_GAME__; g.scene.getScene('Title').scene.start('Game',{floor:20,difficulty:0}); });
await new Promise(r=>setTimeout(r,2600));
const d = await page.evaluate(()=>{ const s=window.__PHASER_GAME__.scene.getScene('Game'); const b=s.boss; const body=b.body;
  return { by:b.y, dh:b.displayHeight, spriteBottom:b.y+b.displayHeight/2, bodyBottom:body.bottom, groundY:432, scale:b.scaleX }; });
console.log(JSON.stringify(d));
await page.evaluate(()=>{ const s=window.__PHASER_GAME__.scene.getScene('Game'); s.player.x = s.boss.x - 80; });
await new Promise(r=>setTimeout(r,400));
await page.screenshot({ path:'/tmp/floor20.png' });
await browser.close();
